### ISSUE TITLE
Versie 2.2 implementeren

### ISSUE THREAD

**Issue by odegroot** [Azure/Bio-Compliancy#13]
In maart 2023 heeft het CIP versie 2.2 van de BIO Thema-uitwerking Clouddiensten als definitief vrijgegeven.
Bron:
https://cip-overheid.nl/productcategorieen-en-workshops/producten?product=Clouddiensten → [Download Clouddiensten]

Kan iemand deze nieuwe versie verwerken in de ARM-templates van dit project?

**Comment by MathieuRietman** [comment]
Is onderdeel van de Juni update. Staat pull request klaar met verwerking en updates van de policies. #14

**Comment by MathieuRietman** [comment]
Hi Oscar thanks for this it is part now of the latest update.
