### ISSUE TITLE
Unable to deploy policyset after removal of older version

### ISSUE THREAD

**Issue by rickpeters** [Azure/Bio-Compliancy#15]
I succesfully deleted a previous version of this policyset in Azure. But now I want to redeploy the new version and I get an error in deployment which references defined parameters which are not used anymore by the current policyset:
```
The policy set '<null>' has defined parameters 'effect-cc9835f2-9f6b-4cc8-ab4a-f8ef615eb349,effect-991310cd-e9f3-47bc-b7b6-f57b557d07db,effect-88999f4c-376a-45c8-bcb3-4058f713cf39,effect-74c3584d-afae-46f7-a20a-6f8adba71a16,effect-1bc1795e-d44a-4d48-9b3b-6fff0fd5f9ba,effect-9a1b8c48-453a-4044-86c3-d8bfd823e4f5,effect-b7ddfbdc-1260-477d-91fd-98bd9be789a6,effect-8cb6aa8b-9e41-4f4e-aa25-089a7ac2581e,effect-52630df9-ca7e-442b-853b-c6ce548b31a2,effect-40cec1dd-a100-4920-b15b-3024fe8901ab,effect-5f0bc445-3935-4915-9981-011aa2b46147,effect-53503636-bcc9-4748-9663-5348217f160f,effect-ebb62a0c-3560-49e1-89ed-27e074e9f8ad,effect-c4d441f8-f9d9-4a9e-9cef-e82117cb3eef,effect-5f76cf89-fbf2-47fd-a3f4-b891fa780b60,effect-5c607a2e-c700-4744-8254-d77e7c9eb5e4,effect-f8456c1c-aa66-4dfb-861a-25d127b775c9,effect-6b1cbf55-e8b6-442f-ba4c-7246b6381474,effect-e3576e28-8b17-4677-84c3-db2990658d64,effect-9297c21d-2ed6-4474-b48f-163f75654ce3,effect-aa633080-8b72-40c4-a2d7-d00c03e80bed,effect-7c1b1214-f927-48bf-8882-84f0af6588b1,includeAKSClusters,effect-b607c5de-e7d9-4eee-9e5c-83f1bcee4fa0' which are not used in referenced policy definitions. Please either remove these parameters from the definition or ensure that they are used. (Code: UnusedPolicyParameters)
```
After reading the README.md I guess that I should have only redeployed the new version and not remove the old version. I see there is a mechanism in place to prevent redeployment issues by keeping unused parameters in the set as deprecated to prevent deployment problems of newwer versions.

However I could not find any instruction on how to solve this problem and also not on how to succesfully remove the BIO compliance policyset in full and reinstall a current version.

**Comment by MathieuRietman** [comment]
We split into separate deployments to update existing deployment of the previous version of the BIO policy or new deployment. Update works when a policy is already deployed on subscription or management group level. If you are deploy it to subscription or management group that has no previous deployment of the policy use the normal. See pull request  #18
