### ISSUE TITLE
Workaround for fresh deployment 2.2.1

### ISSUE THREAD

**Issue by aggerritsen** [Azure/Bio-Compliancy#19]
Is seems that deprecated parameters are stil in the code, only allowing for updates from previous versions. The workaround exist of removing the parameters on the JOSN files which the deployment fails. These are usually marked in the description as [[Deprecated] is their DisplayName, except for 'includeAKSClusters'. Some deprecated parameters are still in use: 'listOfLocations', 'JavaLatestVersion', 'PHPLatestVersion' and 'WindowsPythonLatestVersion'.

After cleaning the code, run New-AzManagementGroupDeployment or New-AzDeployment

**Comment by MathieuRietman** [comment]
We split into separate deployments to update existing deployment of the previous version of the BIO policy or new deployment. Update works when a policy is already deployed on subscription or management group level. If you are deploy it to subscription or management group that has no previous deployment of the policy use the normal. See pull request  #18
