### ISSUE TITLE
Disable Redundant Policy Checking for Obsolete Azure Defender for DNS Plan (deprecated)

### ISSUE THREAD

**Issue by thijsrws** [Azure/Bio-Compliancy#22]
A policy, identified by the ID /providers/Microsoft.Authorization/policyDefinitions/bdc59948-5574-49b3-bb91-76b7c986428d, is currently in place within Azure to check the activation status of the Azure Defender for DNS plan. This policy has become redundant as the Azure Defender for DNS plan has been integrated into a server plan2 , making the standalone plan and its associated check obsolete.

Proposal for Change:
It is proposed that the policy /providers/Microsoft.Authorization/policyDefinitions/bdc59948-5574-49b3-bb91-76b7c986428d, which checks for the activation of the Azure Defender for DNS standalone plan, be disabled or removed from Azure's policy definitions. This change will reflect the current state of Azure services more accurately.

**Comment by MathieuRietman** [comment]
Will be fixed in #25
