### ISSUE TITLE
Add some Front Door policy's

### ISSUE THREAD

**Issue by cschipper1** [Azure/Bio-Compliancy#24]
Can some Front door policy's be added to the initiative:
8a04f872-51e9-4313-97fb-fc1c35430fd8	
Azure Front Door should have Resource logs enabled

cd906338-3453-47ba-9334-2d654bf845af
Azure Front Door Standard or Premium (Plus WAF) should have resource logs enabled

dfc212af-17ea-423a-9dcb-91e2cb2caa6b
Azure Front Door profiles should use Premium tier that supports managed WAF rules and private link

679da822-78a7-4eff-8fff-a899454a9970
Azure Front Door Standard and Premium should be running minimum TLS version of 1.2

**Comment by MathieuRietman** [comment]
Wil be fixed in #25
