### ISSUE TITLE
Documentatie foutjes

### ISSUE THREAD

**Issue by jbarrancos** [Azure/Bio-Compliancy#26]
**[/README.md](https://github.com/Azure/Bio-Compliancy/blob/main/README.md)**

Implementeren op Azure: 
Versie staat nog op 2.2.1 en zou bijgewerkt moeten worden naar 2.2.2.

**[/docs/README.md](https://github.com/Azure/Bio-Compliancy/blob/main/docs/README.md)**

**De mapping van de Azure policies die gebruikt voor deze template zijn beschikbaar in:**
Link is fout. Deze moet bijgewerkt worden naar 2.2.2 **[BIO Control Policy mapping excel]**

**Andere topics:** 
_De BIO policy is ook build beschikbaar deze is het engels en kan afwijken van deze repository. Het de planning dat de build policy deze repository gaat vervangen, nu is de keuze nog tussen de NL versie deze repository en de Engelse nuild in versie._

Deze zinnen lopen niet lekker.

**Comment by MathieuRietman** [comment]
Thanks for raising this issue. This will be fixed in update #32
