### ISSUE TITLE
Migrate away from Log Analytics agent

### ISSUE THREAD

**Issue by odegroot** [Azure/Bio-Compliancy#29]
De _Log Analytics agent_ wordt binnenkort deprecated.

> The Log Analytics agent is on a deprecation path and won't be supported after August 31, 2024.

https://learn.microsoft.com/en-us/azure/azure-monitor/agents/log-analytics-agent
https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration

Kunnen de BIO-policies hierin meegaan, dus dat ook BIO adviseert om de nieuwe agent (_Azure Monitor Agent_) te gebruiken, in plaats van de oude agent?

**Comment by pt0x** [comment]
+1

Een flink aantal policy definities gaat vervangen worden, voorbeeld:

Oud:
- Endpoint Protection not installed on Azure VMs
Nieuw:
- EDR solution should be installed on Virtual Machines

Tevens zijn er policy templates die helemaal niet meer relevant zullen zijn wanneer de log analytics agent deprecated raak per augustus dit jaar, maar nog wel onderdeel zijn van de BIO Compliancy versie 2.2.2

Aantal voorbeelden:
- Auto provisioning of the Log Analytics agent should be enabled on subscriptions
- [Preview]: Log Analytics Extension should be enabled for listed virtual machine images
- Log Analytics extension should be enabled in virtual machine scale sets for listed virtual machine images

**Comment by MathieuRietman** [comment]
Thanks for raising this issue. This will be fixed in update #32
