### ISSUE TITLE
Update request - Unified Disk Encryption recommendations

### ISSUE THREAD

**Issue by pt0x** [Azure/Bio-Compliancy#30]
Per april 2024 gaan "Unified Disk Encryption recommendations" GA. [Bron](https://learn.microsoft.com/en-us/azure/defender-for-cloud/upcoming-changes#general-availability-of-unified-disk-encryption-recommendations)

De BIO Compliancy (versie 2.2.2) gebruikt op dit moment nog policy definitions die hier niet op gebaseerd zijn. Daarom staat er bij bepaalde recommendations de volgende tekst:

> This recommendation will soon be deprecated. [Learn more](https://learn.microsoft.com/en-us/azure/defender-for-cloud/upcoming-changes)

Niet bij alle relevante recommendations staat deze tekst maar gezien de nieuwe policy definitions gaan controleren op het bestaan van Azure disk encryption "**of**" Encryption at host zou in een nieuwe versie van de BIO Compliancy template de volgende zaken moeten worden aangepast.

Verwijderen: (Deprecated)
- Virtual machines should encrypt temp disks, caches, and data flows between Compute and Storage resources
- Virtual machines and virtual machine scale sets should have encryption at host enabled

Toevoegen: (Estimated GA - 30 April 2024)
- Linux virtual machines should enable Azure Disk Encryption or EncryptionAtHost
- Windows virtual machines should enable Azure Disk Encryption or EncryptionAtHost

**Comment by MathieuRietman** [comment]
Thanks for raising this issue. This will be fixed in update #32
