### ISSUE TITLE
Add another policy for Azure Backup should be enabled for Virtual Machines

### ISSUE THREAD

**Issue by keesmod** [Azure/Bio-Compliancy#6]
Please add the following policy to the set:
98d0b9f8-fd90-49c9-88e2-d3baf3b0dd86

So that we can use the exclusionTags for resources that do not require backup. This is not possible with the already included policy for VM Backup:
013e242c-8828-4970-87b3-ab247555486d

Thanks!

**Comment by MathieuRietman** [comment]
We want only audit, deny or disabled policies in the policy initiative this to prevent that we require a managed identity for the policy initiative. This is not required for audit, deny or disabled policies, result in we will not have deploy if not exist policies in this policy initiative.

**Comment by MathieuRietman** [comment]
Closing as not planned
